TRUNCATE TABLE `tutoring`.`tutor`;
INSERT INTO `tutoring`.`tutor` (`email`, `pass`, `first_name`, `last_name`, `intro`, `tutor_img`, `zip_code`) VALUES ('email', 'pass', 'Patrick', 'Stephenson', 'Experience teaching English.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Po9dhsPThMg_D2j5q-PPFAHaFE%26pid%3DApi&f=1', '89521'), 
('tutor@emai', 'pass', 'Omari', 'West', 'I have 20+ years of experience in  the music industry and I can help you make your own music.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftownsquare.media%2Fsite%2F252%2Ffiles%2F2016%2F08%2Fkanye-west-vma-speech-reaction1.jpg%3Fw%3D1200%26h%3D0%26zc%3D1%26s%3D0%26a%3Dt%26q%3D89&f=1&nofb=1', '12345'),
('email', 'pass', 'Yu Bin', 'Lee', 'I am a singer and songwriter. I have several certifications and I am happy to help you do the same.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg.quizur.com%2Ff%2Fimg5f6a0988253623.83560874.jpg%3FlastEdited%3D1600784782&f=1&nofb=1', '31124'),
('email', 'pass', 'Andrew', 'Ng', 'I have woked with AI since 2010 and have created several libraries. I can teach you how to start from Scratch.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwp.technologyreview.com%2Fwp-content%2Fuploads%2F2017%2F12%2Fandrewng_1-7.jpg&f=1&nofb=1', '11544'),
('email', 'word', 'John', 'Doe', 'I have like 5 PhDs in Science, from Biology, Physics, Chemistry, etc. I have 10+ years of experience as a teacher.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.westminster.net%2Fuploaded%2Fnews_and_events%2Fimages_2017-18%2Faugust_2017%2FAdrian-Dingle-Chemistry-Teacher.jpg&f=1&nofb=1', '11547'),
('domain.com', 'qwerty', 'Jane ', 'Doe', 'I studied Physiotherapy and have experience with professional athletes.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmilehighspine.com%2Fwp-content%2Fuploads%2FBackHealth5.jpg&f=1&nofb=1', '12036'),
('address', 'asdwq', 'Mónica', 'Hernández', 'I am a developer and I specialize in game development.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftvline.com%2Fwp-content%2Fuploads%2F2021%2F02%2Fwandavision-darcy-kat-dennings.jpg%3Fresize%3D200&f=1&nofb=1', '20215');

